# Generated by Django 3.1.7 on 2021-10-23 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=150, verbose_name='Pasa tiempo')),
            ],
            options={
                'verbose_name': 'Hobby',
                'verbose_name_plural': 'hobbies',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('job', models.CharField(blank=True, max_length=30, verbose_name='Trabajo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='telefono')),
                ('hobbies', models.ManyToManyField(to='integers.Hobby')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('asunto', models.CharField(max_length=100, verbose_name='Aunto de reunion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integers.person')),
            ],
            options={
                'verbose_name': 'Reunion',
                'verbose_name_plural': 'Reunion',
            },
        ),
    ]
